apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: interview-tool
  annotations:
    meta.version: "v1"
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: user
        image: mastercruelty/docker-hosted:interview_user
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /certificates/public/
          name: public-pem
        - mountPath: /certificates/private/
          name: private-pem
        env:
        - name: MYSQL_HOST
          value: db-user-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
      volumes:
      - name: public-pem
        secret:
          secretName: public-key
      - name: private-pem
        secret:
          secretName: private-key        
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: interview-tool
spec:
  selector:
    app: user
  ports:
  - name: user-service
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-autoscaler
  namespace: interview-tool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
